# Site settings
name: SD Simplified
title: Speech & Debate Simplified
description: The first online Speech & Debate course built to provide you with a low-impact intro to Speech & Debate
url: https://sdsimplified.com/
baseurl: ''
email: arivgups@gmail.com
cover: https://sdsimplified.github.io/img/og.png
logo: https://sdsimplified.github.io/img/icon.png
resume: https://sdsimplified.github.io/resume.pdf
social:
  - title: email
    url: mailto:sdsimplified@gmail.com
  - title: instagram
    url: https://www.instagram.com/sdsimplified/
  - title: twitter
    url: https://twitter.com/SimplifiedSD
  - title: facebook
    url: https://www.facebook.com/SD-Simplified-104980451611550
navbar:
  - title: home
    url: https://www.sdsimplified.com
  - title: bootcamp
    url: https://www.sdsimplified.com/bootcamp
  - title: courses
    url: https://www.udemy.com/user/sd-simplified/
  - title: 1-on-1
    url: https://sdsimplified.setmore.com/beta
#Google Analytics
google_analytics: UA-203130337-1

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap